### ISSUE TITLE
missing ../assets/executor.bundle.js

### ISSUE THREAD

**Issue by pavlelekic** [talyssonoc/php-babel-transpiler#1]
Warning: file_get_contents(): Filename cannot be empty in talyssonoc/php-babel-transpiler/src/Transpiler.php on line 56

I checked and ../assets/executor.bundle.js is really not there. I don't know what should be there, or how does this work, can you please help me out?

Thanks.

**Comment by talyssonoc** [comment]
Have you run  `composer install`? [Babel and Browserify dependencies](https://github.com/talyssonoc/php-babel-transpiler/blob/master/composer.json#L10) are downloaded by [composer-extra-assets](https://github.com/talyssonoc/php-babel-transpiler/blob/master/composer.json#L6) and [executor.bundle.js](https://github.com/talyssonoc/php-babel-transpiler/blob/master/composer.json#L18) is created after the `install` comand is run. Hope it helps!

**Comment by pavlelekic** [comment]
Yes, it worked! Thanks! :)
